"""add lesson progress table

Revision ID: b487ad93e371
Revises: 
Create Date: 2026-04-26 15:28:08.335617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b487ad93e371'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'lesson_id', name='unique_lesson_progress')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
        batch_op.alter_column('published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=False))
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_lessons_module'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'modules', ['module_id'], ['id'])
        batch_op.drop_column('order_index')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.drop_constraint(batch_op.f('unique_course_order'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_modules_course'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_modules_course'), 'courses', ['course_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint(batch_op.f('unique_course_order'), ['course_id', 'order_index'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_index', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lessons_module'), 'modules', ['module_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('order')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.alter_column('published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))

    op.drop_table('lesson_progress')
    # ### end Alembic commands ###
